### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Tawhia** [pyspeckit/pyspeckit-tests#16]
Hi there,

I am trying to use the nh3_tests.py file.
On running, I was getting the error as follows:

      _22   xarr11 = pyspeckit.units.SpectroscopicAxis(np.arange(-30,30,0.4),
      _23         unit='km/s', refX=23.694496, refX_unit='GHz', frame='LSRK',
      _---> 24         xtype='Frequency')_
     _TypeError: __new__() got an unexpected keyword argument 'frame'___

 and 

     _22 xarr11 = pyspeckit.units.SpectroscopicAxis(np.arange(-30,30,0.4),
     _23         unit='km/s', refX=23.694496, refX_unit='GHz',
     _--->_ 24         xtype='Frequency')
     _ 25 
     _26_ xarr22 = pyspeckit.units.SpectroscopicAxis(np.arange(-30,30,0.4),

    _TypeError:_ __new__() got an unexpected keyword argument 'xtype'_

I replaced those lines with 
   _xarr11 = pyspeckit.units.SpectroscopicAxis(np.arange(-30,30,0.4),unit='GHz', refX=23.694496,  refX_unit='GHz')_

 _xarr22 = pyspeckit.units.SpectroscopicAxis(np.arange(-30,30,0.4), refX=23.722633335,
        unit='GHz', refX_unit='GHz')_

where i removed certain keywords and change units from km/s to GHz to avoid the error with 

 _UnitConversionError                       Traceback (most recent call last)
 <ipython-input-26-bd426e2244cb> in <module>()
      26         unit='km/s', refX=23.722633335, refX_unit='GHz')
      27 
 ---> 28 xarr = pyspeckit.units.SpectroscopicAxes([xarr11.as_unit('GHz'),xarr22.as_unit('GHz')])
      29 
      30 test_parameters = {

UnitConversionError: 'km / s' (speed) and 'GHz' (frequency) are not convertible_

But after that i reach the point where i cannot handle another error on my own. The next error message is:

Using matplotlib backend: TkAgg
INFO: Renormalizing data by factor 0.000000e+00 to improve fitting procedure [pyspeckit.spectrum.fitters]
WARNING: The multifit keyword is no longer required.  All fits allow for multiple components. [pyspeckit.spectrum.fitters]

Traceback (most recent call last):
  File "/Users/Karolina/anaconda/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/Users/Karolina/anaconda/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/Users/Karolina/anaconda/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/Karolina/anaconda/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file fitters.py, line 280
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-07101bc12af9> in <module>()
     99                         minpars=[2.73,2.73,10,0,-20,0],
    100                         use_lmfit=True,
--> 101                         verbose=False)
    102 
    103                 outs.append(sp.specfit.parinfo.values[:4])

ValueError: zero-size array to reduction operation minimum which has no identity

Thanks in advance.

**Comment by keflavich** [comment]
Great, thanks!  If you'd like, you can turn these changes into a 'pull request'.  To do this, checkout a new branch (`git checkout -b issue16`, for example), make the changes, `git commit` to commit them, and `git push origin issue16` to push them to your github fork.  Then I can turn these suggested changes into a pull request to fix this issue, or you can create a fresh pull request.
